server {
    listen 80;
    root /usr/share/nginx/html;
    location /api/ {
        proxy_pass ${API_PROXY_TARGET}/;
    }
    location /images/ {
        try_files $uri =404;
    }
    location /assets/ {
        try_files $uri =404;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
