server {
    listen 80;
    root /usr/share/nginx/html;
    location = / { return 302 /storefront/; }
    location = /storefront { return 301 /storefront/; }
    location /storefront/api/ {
        proxy_pass ${API_PROXY_TARGET}/;
    }
    location /storefront/images/ {
        try_files $uri =404;
    }
    location /storefront/assets/ {
        try_files $uri =404;
    }
    location /storefront/ {
        try_files $uri $uri/ /storefront/index.html;
    }
}
