name: Publish Docker images
on:
  push:
    branches: [master]
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: storefront-frontend
            path: apps/frontend
          - project: storefront-discord
            path: apps/discord
    steps:
      - uses: actions/checkout@v7
      - uses: docker/setup-buildx-action@v4
      - uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v7
        with:
          context: .
          file: ${{ matrix.path }}/Dockerfile
          push: true
          tags: jackharrhy/${{ matrix.project }}:latest
